// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXbnVmWvVoKgznruBcozfM84ta1w9_Ouo',
    appId: '1:460817987224:web:03b9b6d2522d2d973902ed',
    messagingSenderId: '460817987224',
    projectId: 'final-project-e5878',
    authDomain: 'final-project-e5878.firebaseapp.com',
    storageBucket: 'final-project-e5878.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtMqO8lRFiZVNQNa2fS8dSiAn8Af_0TQk',
    appId: '1:460817987224:android:a583cfec3c678a033902ed',
    messagingSenderId: '460817987224',
    projectId: 'final-project-e5878',
    storageBucket: 'final-project-e5878.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2EQJK5s7MmWZBIRZY8vsckt_4iXC9iwc',
    appId: '1:460817987224:ios:4d16acc6a0619d553902ed',
    messagingSenderId: '460817987224',
    projectId: 'final-project-e5878',
    storageBucket: 'final-project-e5878.appspot.com',
    iosBundleId: 'com.example.finalProjectRentMotoFe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2EQJK5s7MmWZBIRZY8vsckt_4iXC9iwc',
    appId: '1:460817987224:ios:4d16acc6a0619d553902ed',
    messagingSenderId: '460817987224',
    projectId: 'final-project-e5878',
    storageBucket: 'final-project-e5878.appspot.com',
    iosBundleId: 'com.example.finalProjectRentMotoFe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXbnVmWvVoKgznruBcozfM84ta1w9_Ouo',
    appId: '1:460817987224:web:d950f64af797b7093902ed',
    messagingSenderId: '460817987224',
    projectId: 'final-project-e5878',
    authDomain: 'final-project-e5878.firebaseapp.com',
    storageBucket: 'final-project-e5878.appspot.com',
  );
}
